In [1]:
import sys
sys.path.append('../../../bceao/')
from prix.data import *

In [2]:
data = Data('../../../PRIX/IPC_ANNUEL.xls')
df = data.load_data()
df.head()

,Date,Alimentation,"Boissons alcoolisees, Tabac et stupefiants",Habillement,Ameublement,Logement,Sante,Transport,Communication,Loisirs,Enseignement,Hotels et restaurants,Autres biens et services,Ensemble,Mois,Annee,Country
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196,0,BENIN
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196,0,BURKINA FASO
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196,0,COTE D'IVOIRE
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196,0,ENSEMBLE UMOA
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196,0,GUINEE BISSAU

In [3]:
df.tail(20)

,Date,Alimentation,"Boissons alcoolisees, Tabac et stupefiants",Habillement,Ameublement,Logement,Sante,Transport,Communication,Loisirs,Enseignement,Hotels et restaurants,Autres biens et services,Ensemble,Mois,Annee,Country
62,2022,133.7,120.1,106.7,112.4,105.0,110.7,107.9,85.0,110.4,112.8,114.8,108.4,120.4,202,2,SENEGAL
62,2022,108.7,111.8,112.4,111.6,103.2,104.3,113.2,98.8,104.1,103.4,104.1,110.7,107.4,202,2,TOGO
63,2023,108.99,112.78,115.45,114.64,109.75,104.63,126.17,98.72,107.74,104.32,105.3,114.3,110.34,202,3,BENIN
63,2023,138.17,159.98,101.73,102.02,112.73,105.55,109.95,99.03,101.54,114.84,112.22,102.16,124.31,202,3,BURKINA FASO
63,2023,140.26,108.28,111.79,110.81,124.13,105.84,119.15,102.03,103.24,111.33,118.33,112.04,121.65,202,3,COTE D'IVOIRE
63,2023,132.8,126.42,111.39,111.36,117.41,108.36,114.5,97.11,111.15,110.31,118.66,112.94,121.29,202,3,ENSEMBLE UMOA
63,2023,139.13,107.45,101.19,102.9,144.63,101.49,115.69,93.75,98.89,105.04,99.58,98.96,126.89,202,3,GUINEE BISSAU
63,2023,122.98,113.81,112.41,116.31,110.67,122.06,109.42,79.51,136.74,119.79,109.1,124.97,117.73,202,3,MALI
63,2023,123.32,117.56,113.26,108.66,125.36,107.86,104.16,102.35,108.72,97.58,120.55,115.53,117.21,202,3,NIGER
63,2023,143.08,122.83,110.41,116.61,109.99,112.91,112.09,90.1,120.81,114.87,122.14,115.06,127.53,202,3,SENEGAL
63,2023,140.54,117.82,120.07,124.17,114.37,104.14,113.36,101.58,117.39,112.58,134.29,115.75,125.61,202,3,TOGO
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,BENIN
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,BURKINA FASO
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,COTE D'IVOIRE
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,ENSEMBLE UMOA
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,GUINEE BISSAU
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,MALI
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,NIGER
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,SENEGAL
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,TOGO

In [4]:
data = Data('../../../PRIX/INFLATION_MOYENNE_ANNUELLE.xls')
df = data.load_data()
df.head()

,Date,Taux d'inflation en moyenne annuelle de la fonction alimentation,"Taux d'inflation en moyenne annuelle de la fonction Boissons alcoolisees, Tabac et stupefiants",Taux d'inflation en moyenne annuelle de la fonction habillement,Taux d'inflation en moyenne annuelle de la fonction Ameublement,Taux d'inflation en moyenne annuelle de la fonction logement,Taux d'inflation en moyenne annuelle de la fonction Sante,Taux d'inflation en moyenne annuelle de la fonction Transport,Taux d'inflation en moyenne annuelle de la fonction Communication,Taux d'inflation en moyenne annuelle de la fonction Loisirs,Taux d'inflation en moyenne annuelle de la fonction Enseignement,Taux d'inflation en moyenne annuelle de la fonction Hotels et restaurants,Taux d'inflation en moyenne annuelle de la fonction Autres biens et services,Taux d'inflation moyen annuel (IPC) (en %),Mois,Annee,Country
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196,0,BENIN
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196,0,BURKINA FASO
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196,0,COTE D'IVOIRE
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196,0,ENSEMBLE UMOA
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196,0,GUINEE BISSAU

In [5]:
df.tail(20)

,Date,Taux d'inflation en moyenne annuelle de la fonction alimentation,"Taux d'inflation en moyenne annuelle de la fonction Boissons alcoolisees, Tabac et stupefiants",Taux d'inflation en moyenne annuelle de la fonction habillement,Taux d'inflation en moyenne annuelle de la fonction Ameublement,Taux d'inflation en moyenne annuelle de la fonction logement,Taux d'inflation en moyenne annuelle de la fonction Sante,Taux d'inflation en moyenne annuelle de la fonction Transport,Taux d'inflation en moyenne annuelle de la fonction Communication,Taux d'inflation en moyenne annuelle de la fonction Loisirs,Taux d'inflation en moyenne annuelle de la fonction Enseignement,Taux d'inflation en moyenne annuelle de la fonction Hotels et restaurants,Taux d'inflation en moyenne annuelle de la fonction Autres biens et services,Taux d'inflation moyen annuel (IPC) (en %),Mois,Annee,Country
62,2022,15.1,3.5,3.7,4.1,4.3,2.2,2.3,-1.8,8.7,1.7,6.2,3.3,9.7,202,2,SENEGAL
62,2022,11.2,4.8,5.3,8.3,5.7,0.5,12.7,-0.2,8.2,-1.0,4.5,3.7,7.6,202,2,TOGO
63,2023,0.3,0.9,2.7,6.4,2.7,0.3,11.5,-0.1,3.5,0.9,1.1,3.3,2.7,202,3,BENIN
63,2023,-1.8,6.4,0.1,9.2,0.3,4.9,6.4,0.3,0.1,2.0,4.1,0.3,0.7,202,3,BURKINA FASO
63,2023,6.4,1.7,1.8,4.3,2.0,1.0,8.2,0.5,0.8,0.5,5.6,1.4,4.4,202,3,COTE D'IVOIRE
63,2023,3.7,4.12,2.31,4.69,2.79,1.14,6.71,0.51,3.58,1.1,5.73,2.7,3.7,202,3,ENSEMBLE UMOA
63,2023,9.6,5.3,1.2,12.5,-0.1,1.9,4.4,-1.5,0.3,-1.0,-1.1,-1.1,7.2,202,3,GUINEE BISSAU
63,2023,2.1,2.7,1.8,0.3,2.8,-0.9,4.7,-2.7,4.6,4.4,3.1,4.9,2.1,202,3,MALI
63,2023,4.3,7.0,2.1,5.4,4.0,1.8,2.3,0.6,3.5,0.0,2.4,4.5,3.7,202,3,NIGER
63,2023,6.99,2.25,3.44,4.77,3.74,1.95,3.89,5.97,9.41,1.83,6.37,6.12,5.9,202,3,SENEGAL
63,2023,3.51,3.92,5.85,5.22,5.63,0.1,7.91,-0.08,4.35,2.64,12.17,3.11,5.3,202,3,TOGO
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,BENIN
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,BURKINA FASO
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,COTE D'IVOIRE
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,ENSEMBLE UMOA
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,GUINEE BISSAU
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,MALI
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,NIGER
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,SENEGAL
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202,4,TOGO

In [6]:
data = Data('../../../PRIX/INFLATION_GLISSEMENT_ANNUEL.xls')
df = data.load_data()
df.head()

,Date,Taux d'inflation en glissement annuel de la fonction alimentation,"Taux d'inflation en glissement annuel de la fonction Boissons alcoolisees, Tabac et stupefiants",Taux d'inflation en glissement annuel de la fonction habillement,Taux d'inflation en glissement annuel de la fonction Ameublement,Taux d'inflation en glissement annuel de la fonction logement,Taux d'inflation en glissement annuel de la fonction Sante,Taux d'inflation en glissement annuel de la fonction Transport,Taux d'inflation en glissement annuel de la fonction Communication,Taux d'inflation en glissement annuel de la fonction Loisirs,Taux d'inflation en glissement annuel de la fonction Enseignement,Taux d'inflation en glissement annuel de la fonction Hotels et restaurants,Taux d'inflation en glissement annuel de la fonction Autres biens et services,Taux d'inflation en glissement annuel-Indice global,Mois,Annee,Country
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUG,1960,BENIN
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUG,1960,BURKINA FASO
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUG,1960,COTE D'IVOIRE
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUG,1960,ENSEMBLE UMOA
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUG,1960,GUINEE BISSAU

In [7]:
df.tail(20)

,Date,Taux d'inflation en glissement annuel de la fonction alimentation,"Taux d'inflation en glissement annuel de la fonction Boissons alcoolisees, Tabac et stupefiants",Taux d'inflation en glissement annuel de la fonction habillement,Taux d'inflation en glissement annuel de la fonction Ameublement,Taux d'inflation en glissement annuel de la fonction logement,Taux d'inflation en glissement annuel de la fonction Sante,Taux d'inflation en glissement annuel de la fonction Transport,Taux d'inflation en glissement annuel de la fonction Communication,Taux d'inflation en glissement annuel de la fonction Loisirs,Taux d'inflation en glissement annuel de la fonction Enseignement,Taux d'inflation en glissement annuel de la fonction Hotels et restaurants,Taux d'inflation en glissement annuel de la fonction Autres biens et services,Taux d'inflation en glissement annuel-Indice global,Mois,Annee,Country
752,SEP2022,18.2,4.4,4.2,4.5,4.7,3.4,2.4,-2.5,14.9,1.6,7.4,4.0,11.9,SEP,2022,SENEGAL
752,SEP2022,8.6,9.5,6.7,11.0,8.1,1.0,17.3,-0.3,8.4,2.0,5.6,4.5,7.9,SEP,2022,TOGO
764,SEP2023,-4.95,-0.84,2.76,7.0,2.33,0.03,16.52,-0.01,3.08,0.71,1.52,4.36,1.51,SEP,2023,BENIN
764,SEP2023,-6.8,-0.15,0.02,8.99,0.41,5.89,4.22,0.63,-0.37,1.72,5.36,0.14,-2.56,SEP,2023,BURKINA FASO
764,SEP2023,6.52,0.9,1.47,4.06,1.3,1.69,7.92,0.49,0.65,0.51,4.44,1.12,4.23,SEP,2023,COTE D'IVOIRE
764,SEP2023,2.27,0.82,2.06,3.72,2.18,1.49,5.99,0.49,1.95,1.37,5.04,2.37,2.74,SEP,2023,ENSEMBLE UMOA
764,SEP2023,6.22,35.88,7.56,-22.81,43.16,2.89,-12.97,21.72,-5.97,-6.92,4.64,-0.96,4.74,SEP,2023,GUINEE BISSAU
764,SEP2023,-0.63,2.09,1.8,-5.26,2.37,0.17,2.32,-3.68,1.6,12.81,1.03,3.54,-0.38,SEP,2023,MALI
764,SEP2023,12.45,4.16,2.7,6.78,3.6,2.1,2.39,0.5,1.81,-0.03,1.46,3.55,7.79,SEP,2023,NIGER
764,SEP2023,4.01,1.2,2.48,3.27,2.75,0.86,3.36,7.24,4.65,1.91,4.45,5.86,3.77,SEP,2023,SENEGAL
764,SEP2023,1.69,-0.74,5.0,3.63,3.78,0.04,2.22,-0.03,3.31,1.42,11.19,2.11,3.6,SEP,2023,TOGO
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SEP,2024,BENIN
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SEP,2024,BURKINA FASO
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SEP,2024,COTE D'IVOIRE
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SEP,2024,ENSEMBLE UMOA
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SEP,2024,GUINEE BISSAU
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SEP,2024,MALI
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SEP,2024,NIGER
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SEP,2024,SENEGAL
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SEP,2024,TOGO

In [8]:
data = Data('../../../PRIX/IPC_MENSUEL.xls')
df = data.load_data()
df.head()

,Date,Alimentation,"Boissons alcoolisees, Tabac et stupefiants",Habillement,Ameublement,Logement,Sante,Transport,Communication,Loisirs,Enseignement,Hotels et restaurants,Autres biens et services,Ensemble,Mois,Annee,Country,SSSSR3023M0BP,SSSSR3029M0BP,SSSSR3030M0BP
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUG,1960,BENIN,NaN,NaN,NaN
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUG,1960,BURKINA FASO,NaN,NaN,NaN
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUG,1960,COTE D'IVOIRE,NaN,NaN,NaN
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUG,1960,ENSEMBLE UMOA,NaN,NaN,NaN
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUG,1960,GUINEE BISSAU,NaN,NaN,NaN