In [1]:
import sys
sys.path.append('../../../bceao/')
from prix.data import *

data = Data('../../../PRIX/IPC_MENSUEL.xls')
df = data.load_data()
df.head()

,Date,Alimentation,"Boissons alcoolisees, Tabac et stupefiants",Habillement,Ameublement,Logement,Sante,Transport,Communication,Loisirs,Enseignement,Hotels et restaurants,Autres biens et services,Ensemble,Mois,Annee,Country
0,JAN1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,1960,BENIN
0,JAN1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,1960,BURKINA FASO
0,JAN1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,1960,COTE D'IVOIRE
0,JAN1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,1960,ENSEMBLE UMOA
0,JAN1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,1960,GUINEE BISSAU

In [2]:
df.tail(20)

,Date,Alimentation,"Boissons alcoolisees, Tabac et stupefiants",Habillement,Ameublement,Logement,Sante,Transport,Communication,Loisirs,Enseignement,Hotels et restaurants,Autres biens et services,Ensemble,Mois,Annee,Country
779,DEC2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,2024,SENEGAL
779,DEC2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,2024,TOGO
772,MAY2024,113.36,110.22,116.28,115.95,114.88,106.13,128.06,97.98,109.51,104.35,108.45,115.19,113.28,NaN,2024,BENIN
775,AUG2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,BENIN
772,MAY2024,144.6,161.6,101.8,102.1,118.0,106.6,110.6,99.4,102.0,117.1,114.1,102.7,128.3,NaN,2024,BURKINA FASO
775,AUG2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,BURKINA FASO
772,MAY2024,149.2,109.9,113.1,113.5,131.3,108.2,122.7,103.1,104.7,110.6,120.2,113.8,126.3,NaN,2024,COTE D'IVOIRE
775,AUG2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,COTE D'IVOIRE
772,MAY2024,139.0,128.8,112.9,114.7,121.1,111.8,116.2,98.0,112.7,110.8,123.3,115.8,125.4,NaN,2024,ENSEMBLE UMOA
775,AUG2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,ENSEMBLE UMOA
772,MAY2024,143.3,108.2,101.2,102.8,188.9,102.4,115.6,92.7,98.7,107.3,97.9,99.5,131.4,NaN,2024,GUINEE BISSAU
775,AUG2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,GUINEE BISSAU
772,MAY2024,124.0,130.4,114.8,117.2,110.1,135.7,110.0,79.0,140.7,124.1,113.8,128.8,119.2,NaN,2024,MALI
775,AUG2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,MALI
772,MAY2024,140.6,114.3,116.7,117.5,122.6,114.7,102.6,105.5,106.9,96.5,153.3,128.4,128.4,NaN,2024,NIGER
775,AUG2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,NIGER
772,MAY2024,142.0,124.6,111.1,119.2,109.3,113.2,113.3,92.7,123.5,116.3,125.5,118.1,127.6,NaN,2024,SENEGAL
775,AUG2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,SENEGAL
772,MAY2024,154.4,118.4,123.0,126.8,115.9,104.8,115.0,101.4,117.6,116.7,136.7,118.6,131.4,NaN,2024,TOGO
775,AUG2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,TOGO