In [1]:
import sys
sys.path.append('./macrobceao/')
from macrobceao.bceao import *

data = Data('prix mensuels uemoa sans meta.xls')
df = data.load_data()
df.head()

['Alimentation', 'Boissons alcoolisees, Tabac et stupefiants', 'Habillement', 'Ameublement', 'Logement', 'Sante', 'Transport', 'Communication', 'Loisirs', 'Enseignement', 'Hotels et restaurants', 'Autres biens et services', 'Ensemble']
['Alimentation', 'Boissons alcoolisees, Tabac et stupefiants', 'Habillement', 'Ameublement', 'Logement', 'Sante', 'Transport', 'Communication', 'Loisirs', 'Enseignement', 'Hotels et restaurants', 'Autres biens et services', 'Ensemble']
['Alimentation', 'Boissons alcoolisees, Tabac et stupefiants', 'Habillement', 'Ameublement', 'Logement', 'Sante', 'Transport', 'Communication', 'Loisirs', 'Enseignement', 'Hotels et restaurants', 'Autres biens et services', 'Ensemble']
['Alimentation', 'Boissons alcoolisees, Tabac et stupefiants', 'Habillement', 'Ameublement', 'Logement', 'Sante', 'Transport', 'Communication', 'Loisirs', 'Enseignement', 'Hotels et restaurants', 'Autres biens et services', 'Ensemble']
['Alimentation', 'Boissons alcoolisees, Tabac et stupefiants', 'Habillement', 'Ameublement', 'Logement', 'Sante', 'Transport', 'Communication', 'Loisirs', 'Enseignement', 'Hotels et restaurants', 'Autres biens et services', 'Ensemble']
['Alimentation', 'Boissons alcoolisees, Tabac et stupefiants', 'Habillement', 'Ameublement', 'Logement', 'Sante', 'Transport', 'Communication', 'Loisirs', 'Enseignement', 'Hotels et restaurants', 'Autres biens et services', 'Ensemble']
['Alimentation', 'Boissons alcoolisees, Tabac et stupefiants', 'Habillement', 'Ameublement', 'SSSSR3023M0BP', 'Sante', 'Transport', 'Communication', 'Loisirs', 'Enseignement', 'SSSSR3029M0BP', 'SSSSR3030M0BP', 'Ensemble']
['Alimentation', 'Boissons alcoolisees, Tabac et stupefiants', 'Habillement', 'Ameublement', 'Logement', 'Sante', 'Transport', 'Communication', 'Loisirs', 'Enseignement', 'Hotels et restaurants', 'Autres biens et services', 'Ensemble']
['Alimentation', 'Boissons alcoolisees, Tabac et stupefiants', 'Habillement', 'Ameublement', 'Logement', 'Sante', 'Transport', 'Communication', 'Loisirs', 'Enseignement', 'Hotels et restaurants', 'Autres biens et services', 'Ensemble']

,Date,Alimentation,"Boissons alcoolisees, Tabac et stupefiants",Habillement,Ameublement,Logement,Sante,Transport,Communication,Loisirs,Enseignement,Hotels et restaurants,Autres biens et services,Ensemble,Country,SSSSR3023M0BP,SSSSR3029M0BP,SSSSR3030M0BP
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIN,NaN,NaN,NaN
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BURKINA FASO,NaN,NaN,NaN
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COTE D'IVOIRE,NaN,NaN,NaN
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENSEMBLE UMOA,NaN,NaN,NaN
7,AUG1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GUINEE BISSAU,NaN,NaN,NaN

In [2]:
df.shape

(7020, 18)

In [3]:
df.tail(20)

,Date,Alimentation,"Boissons alcoolisees, Tabac et stupefiants",Habillement,Ameublement,Logement,Sante,Transport,Communication,Loisirs,Enseignement,Hotels et restaurants,Autres biens et services,Ensemble,Country,SSSSR3023M0BP,SSSSR3029M0BP,SSSSR3030M0BP
752,SEP2022,144.10,121.70,107.80,113.50,106.10,112.00,108.70,84.30,116.60,112.30,116.80,109.30,126.20,SENEGAL,NaN,NaN,NaN
752,SEP2022,134.60,119.60,115.10,120.30,111.10,104.20,111.70,101.60,113.50,109.80,122.20,113.20,120.50,TOGO,NaN,NaN,NaN
764,SEP2023,99.95,112.12,115.44,114.57,108.93,104.60,131.09,98.69,109.08,104.34,105.75,114.76,107.49,BENIN,NaN,NaN,NaN
764,SEP2023,139.99,156.47,101.72,102.03,116.07,106.54,110.52,99.35,101.14,114.07,113.98,102.40,125.60,BURKINA FASO,NaN,NaN,NaN
764,SEP2023,143.12,108.94,111.72,110.80,125.26,106.91,120.80,102.05,103.30,111.68,119.19,112.15,122.97,COTE D'IVOIRE,NaN,NaN,NaN
764,SEP2023,136.21,125.58,111.63,111.44,117.46,108.46,116.50,97.02,111.69,110.67,119.52,113.14,123.01,ENSEMBLE UMOA,NaN,NaN,NaN
764,SEP2023,138.74,107.50,102.40,102.80,NaN,101.70,115.90,92.70,98.80,105.30,NaN,NaN,126.90,GUINEE BISSAU,147.44,98.1,100.04
764,SEP2023,126.25,112.40,112.90,116.50,104.55,117.60,114.90,78.60,139.30,130.30,108.30,125.65,119.50,MALI,NaN,NaN,NaN
764,SEP2023,135.11,118.02,114.09,108.74,126.54,107.95,104.44,102.34,108.82,97.58,120.64,114.74,123.02,NIGER,NaN,NaN,NaN
764,SEP2023,149.92,123.16,110.49,116.64,109.55,112.98,112.31,90.42,121.97,114.44,122.00,115.73,130.97,SENEGAL,NaN,NaN,NaN
764,SEP2023,136.92,118.67,120.86,124.88,115.16,104.25,114.13,101.55,117.26,111.33,135.88,115.62,124.88,TOGO,NaN,NaN,NaN
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIN,NaN,NaN,NaN
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BURKINA FASO,NaN,NaN,NaN
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COTE D'IVOIRE,NaN,NaN,NaN
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENSEMBLE UMOA,NaN,NaN,NaN
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GUINEE BISSAU,NaN,NaN,NaN
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MALI,NaN,NaN,NaN
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NIGER,NaN,NaN,NaN
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SENEGAL,NaN,NaN,NaN
776,SEP2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOGO,NaN,NaN,NaN