In [1]:
import sys
sys.path.append('../../../bceao/')
from prix.data import *

In [2]:
data = Data('../../../PRIX/IPC_ANNUEL.xls')
df = data.load_data()
df.head()

,Date,Alimentation,"Boissons alcoolisees, Tabac et stupefiants",Habillement,Ameublement,Logement,Sante,Transport,Communication,Loisirs,Enseignement,Hotels et restaurants,Autres biens et services,Ensemble,Country
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIN
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BURKINA FASO
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COTE D'IVOIRE
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENSEMBLE UMOA
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GUINEE BISSAU

In [4]:
df.tail(20)

,Date,Alimentation,"Boissons alcoolisees, Tabac et stupefiants",Habillement,Ameublement,Logement,Sante,Transport,Communication,Loisirs,Enseignement,Hotels et restaurants,Autres biens et services,Ensemble,Country
62,2022,133.7,120.1,106.7,112.4,105.0,110.7,107.9,85.0,110.4,112.8,114.8,108.4,120.4,SENEGAL
62,2022,108.7,111.8,112.4,111.6,103.2,104.3,113.2,98.8,104.1,103.4,104.1,110.7,107.4,TOGO
63,2023,108.99,112.78,115.45,114.64,109.75,104.63,126.17,98.72,107.74,104.32,105.3,114.3,110.34,BENIN
63,2023,138.17,159.98,101.73,102.02,112.73,105.55,109.95,99.03,101.54,114.84,112.22,102.16,124.31,BURKINA FASO
63,2023,140.26,108.28,111.79,110.81,124.13,105.84,119.15,102.03,103.24,111.33,118.33,112.04,121.65,COTE D'IVOIRE
63,2023,132.8,126.42,111.39,111.36,117.41,108.36,114.5,97.11,111.15,110.31,118.66,112.94,121.29,ENSEMBLE UMOA
63,2023,139.13,107.45,101.19,102.9,144.63,101.49,115.69,93.75,98.89,105.04,99.58,98.96,126.89,GUINEE BISSAU
63,2023,122.98,113.81,112.41,116.31,110.67,122.06,109.42,79.51,136.74,119.79,109.1,124.97,117.73,MALI
63,2023,123.32,117.56,113.26,108.66,125.36,107.86,104.16,102.35,108.72,97.58,120.55,115.53,117.21,NIGER
63,2023,143.08,122.83,110.41,116.61,109.99,112.91,112.09,90.1,120.81,114.87,122.14,115.06,127.53,SENEGAL
63,2023,140.54,117.82,120.07,124.17,114.37,104.14,113.36,101.58,117.39,112.58,134.29,115.75,125.61,TOGO
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIN
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BURKINA FASO
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COTE D'IVOIRE
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENSEMBLE UMOA
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GUINEE BISSAU
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MALI
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NIGER
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SENEGAL
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOGO

In [7]:
data = Data('../../../PRIX/INFLATION_MOYENNE_ANNUELLE.xls')
df = data.load_data()
df.head()

,Date,Taux d'inflation en moyenne annuelle de la fonction alimentation,"Taux d'inflation en moyenne annuelle de la fonction Boissons alcoolisees, Tabac et stupefiants",Taux d'inflation en moyenne annuelle de la fonction habillement,Taux d'inflation en moyenne annuelle de la fonction Ameublement,Taux d'inflation en moyenne annuelle de la fonction logement,Taux d'inflation en moyenne annuelle de la fonction Sante,Taux d'inflation en moyenne annuelle de la fonction Transport,Taux d'inflation en moyenne annuelle de la fonction Communication,Taux d'inflation en moyenne annuelle de la fonction Loisirs,Taux d'inflation en moyenne annuelle de la fonction Enseignement,Taux d'inflation en moyenne annuelle de la fonction Hotels et restaurants,Taux d'inflation en moyenne annuelle de la fonction Autres biens et services,Taux d'inflation moyen annuel (IPC) (en %),Country
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIN
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BURKINA FASO
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COTE D'IVOIRE
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENSEMBLE UMOA
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GUINEE BISSAU

In [8]:
df.tail(20)

,Date,Taux d'inflation en moyenne annuelle de la fonction alimentation,"Taux d'inflation en moyenne annuelle de la fonction Boissons alcoolisees, Tabac et stupefiants",Taux d'inflation en moyenne annuelle de la fonction habillement,Taux d'inflation en moyenne annuelle de la fonction Ameublement,Taux d'inflation en moyenne annuelle de la fonction logement,Taux d'inflation en moyenne annuelle de la fonction Sante,Taux d'inflation en moyenne annuelle de la fonction Transport,Taux d'inflation en moyenne annuelle de la fonction Communication,Taux d'inflation en moyenne annuelle de la fonction Loisirs,Taux d'inflation en moyenne annuelle de la fonction Enseignement,Taux d'inflation en moyenne annuelle de la fonction Hotels et restaurants,Taux d'inflation en moyenne annuelle de la fonction Autres biens et services,Taux d'inflation moyen annuel (IPC) (en %),Country
62,2022,15.1,3.5,3.7,4.1,4.3,2.2,2.3,-1.8,8.7,1.7,6.2,3.3,9.7,SENEGAL
62,2022,11.2,4.8,5.3,8.3,5.7,0.5,12.7,-0.2,8.2,-1.0,4.5,3.7,7.6,TOGO
63,2023,0.3,0.9,2.7,6.4,2.7,0.3,11.5,-0.1,3.5,0.9,1.1,3.3,2.7,BENIN
63,2023,-1.8,6.4,0.1,9.2,0.3,4.9,6.4,0.3,0.1,2.0,4.1,0.3,0.7,BURKINA FASO
63,2023,6.4,1.7,1.8,4.3,2.0,1.0,8.2,0.5,0.8,0.5,5.6,1.4,4.4,COTE D'IVOIRE
63,2023,3.7,4.12,2.31,4.69,2.79,1.14,6.71,0.51,3.58,1.1,5.73,2.7,3.7,ENSEMBLE UMOA
63,2023,9.6,5.3,1.2,12.5,-0.1,1.9,4.4,-1.5,0.3,-1.0,-1.1,-1.1,7.2,GUINEE BISSAU
63,2023,2.1,2.7,1.8,0.3,2.8,-0.9,4.7,-2.7,4.6,4.4,3.1,4.9,2.1,MALI
63,2023,4.3,7.0,2.1,5.4,4.0,1.8,2.3,0.6,3.5,0.0,2.4,4.5,3.7,NIGER
63,2023,6.99,2.25,3.44,4.77,3.74,1.95,3.89,5.97,9.41,1.83,6.37,6.12,5.9,SENEGAL
63,2023,3.51,3.92,5.85,5.22,5.63,0.1,7.91,-0.08,4.35,2.64,12.17,3.11,5.3,TOGO
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIN
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BURKINA FASO
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COTE D'IVOIRE
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENSEMBLE UMOA
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GUINEE BISSAU
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MALI
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NIGER
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SENEGAL
64,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOGO